publications = [
    {"title": "Detection of Cosmological 21 cm Emission with the Canadian Hydrogen Intensity Mapping Experiment",
    "url": "https://arxiv.org/abs/2202.01242",
    "note": "CHIME Collaboration (arXiv:2202.01242)"},
    {"title": "An Overview of CHIME, the Canadian Hydrogen Intensity Mapping Experiment",
    "url": "https://arxiv.org/abs/2201.07869",
    "note": "CHIME Collaboration (arXiv:2201.07869)"},
    {"title": "Using the Sun to Measure the Primary Beam Response of the Canadian Hydrogen Intensity Mapping Experiment",
    "url": "https://arxiv.org/abs/2201.11822",
    "note": "CHIME Collaboration (arXiv:2201.11822)"},
    {"title": "The First CHIME/FRB Fast Radio Burst Catalog",
    "url": "https://arxiv.org/abs/2106.04352",
    "note": "CHIME/FRB Collaboration (arXiv:2106.04352)"},
    {"title": "No Evidence for Galactic Latitude Dependence of the Fast Radio Burst Sky Distrubution",
    "url": "https://arxiv.org/abs/2106.04353",
    "note": "Josephy, A. et al., (arXiv:2106.04353)"},
    {"title": "CHIME/FRB Catalog 1 results: statistical cross-correlations with large-scale structure",
    "url": "https://arxiv.org/abs/2106.04354",
    "note": "Rafiei-Ravandi, M. et al., (arXiv:2106.04354)"},
    {"title": "Fast radio burst morphology in the first CHIME/FRB catalog",
    "url": "https://arxiv.org/abs/2106.04356",
    "note": "Pleunis, Z. et al., (arXiv:2106.04356)"},
    {"title": "Refined Mass and Geometric Measurements of the High-Mass PSR J0740+6620",
    "url": "https://arxiv.org/abs/2104.00880",
    "note": "E. Fonseca et al. (arXiv:2104.00880)"},
    {"title": "First discovery of new pulsars and RRATs with CHIME/FRB",
    "url": "https://arxiv.org/abs/2012.02320",
    "note": "D. C. Good et al. (arXiv:2012.02320)"},
    {"title": "The CHIME Pulsar Project: System Overview",
    "url": "https://arxiv.org/abs/2008.05681",
    "note": "CHIME/Pulsar Collaboration (arXiv:2008.05681)"},
    {"title": "Confirmation of a change in the emission properties of PSR J1713+0747",
    "url": "https://www.astronomerstelegram.org/?read=14652",
    "note": "B. Meyers for the CHIME/Pulsar Collaboration (ATEL #14652)"},
    {"title": "Non-detection of radio pulsations from SGR1935+2154 by CHIME/Pulsar",
    "url": "https://www.astronomerstelegram.org/?read=13838",
    "note": "C. M. Tan for the CHIME/Pulsar Collaboration (ATEL #13838)"},
    {"title": "Periodic activity from a fast radio burst source",
    "url": "https://ui.adsabs.harvard.edu/abs/2020Natur.582..351C/abstract",
    "note": "CHIME/FRB Collaboration, Nature, 582, 351"},
    {"title": "Faraday rotation measures of Northern hemisphere pulsars using CHIME/Pulsar",
    "url": "https://ui.adsabs.harvard.edu/abs/2020MNRAS.496.2836N/abstract",
    "note": "Ng, C. et al., MNRAS, 496, 2836"},
    {"title": "A bright millisecond-duration radio burst from a Galactic magnetar",
    "url": "https://ui.adsabs.harvard.edu/abs/2020arXiv200510324T/abstract",
    "note": "CHIME/FRB Collaboration, Nature, submitted (arXiv:2005.10324)"},
    {"title": "Nine New Repeating Fast Radio Burst Sources from CHIME/FRB",
    "url": "https://ui.adsabs.harvard.edu/abs/2020ApJ...891L...6F/abstract",
    "note": "Fonseca, E. et al., Astrophys. J., 891, L6"},
    {"title": "CHIME/FRB Discovery of Eight New Repeating Fast Radio Burst Sources",
    "url": "https://ui.adsabs.harvard.edu/abs/2019ApJ...885L..24C/abstract",
    "note": "CHIME/FRB Collaboration et al., Astrophys. J., 885, L24"},
    {"title": "CHIME/FRB Detection of the Original Repeating Fast Radio Burst Source FRB 121102",
    "url": "https://ui.adsabs.harvard.edu/abs/2019ApJ...882L..18J/abstract",
    "note": "Josephy, A. et al., Astrophys. J., 882, L18"},
    {"title": "A Second Source of Repeating Fast Radio Bursts",
    "url": "http://adsabs.harvard.edu/abs/2019arXiv190104525T",
    "note": "The CHIME/FRB Collaboration, 2019, Nature, 566, 236"},
    {"title": "Observations of Fast Radio Bursts at Frequencies down to 400 Megahertz",
    "url": "http://adsabs.harvard.edu/abs/2019arXiv190104524C",
    "note": "The CHIME/FRB Collaboration, 2019, Nature, 566, 230"},
    {"title": "The CHIME Fast Radio Burst Project: System Overview",
    "url": "http://adsabs.harvard.edu/abs/2018ApJ...863...48T",
    "note": "The CHIME/FRB Collaboration, 2018, ApJ, 863, 48"},
    {"title": "First detection of fast radio bursts between 400 and 800 MHz by CHIME/FRB",
    "url": "http://www.astronomerstelegram.org/?read=11901",
    "note": "The CHIME/FRB Collaboration, 2018, ATEL #11901"},
    {"title": "The cloverleaf antenna: A compact wide-bandwidth dual-polarization feed for CHIME",
    "url": "https://arxiv.org/abs/1708.08521",
    "note": "Deng, M. et al. 2014, 16th International Symposium on Antenna Technology and Applied Electromagnetics, 1"},
    {"title": "Limits on the ultra-bright Fast Radio Burst population from the CHIME Pathfinder",
    "url": "https://arxiv.org/abs/1702.08040",
    "note": "Amiri et al. 2017, Astrophys. J. 844, 161"},
    {"title": "CHIME FRB: An application of FFT beamforming for a radio telescope",
    "url": "https://arxiv.org/abs/1702.04728",
    "note": "Ng, C. et al., 2017, accepted to XXXIInd International Union of Radio Science General Assembly & Scientific Symposium"},
    {"title": "ICE: A Scalable, Low-Cost FPGA-Based Telescope Signal Processing and Networking System",
    "url": "https://arxiv.org/abs/1608.06262",
    "note": "Bandura et al. 2016, Journal of Astronomical Instrumentation, 5, 1641005"},
    {"title": "Holographic Beam Mapping of the CHIME Pathfinder Array",
    "url": "https://arxiv.org/abs/1607.01473",
    "note": "Berger et al. 2016, Proc. SPIE, 9906, 99060D"},
    {"title": "A compression scheme for radio data in high performance computing",
    "url": "https://arxiv.org/abs/1503.00638",
    "note": "Masui et al. 2015, Astronomy & Computing, 12, 181"},
    {"title": "GPU Kernels for High-Speed 4-Bit Astrophysical Data Processing",
    "url": "https://arxiv.org/abs/1503.06203",
    "note": "Klages et al. 2015, IEEE ASAP Conference"},
    {"title": "A GPU-based Correlator X-engine Implemented on the CHIME Pathfinder",
    "url": "https://arxiv.org/abs/1503.06202",
    "note": "Denman et al. 2015, IEEE ASAP Conference"},
    {"title": "An Efficient Real-time Data Pipeline for the CHIME Pathfinder X-engine",
    "url": "https://arxiv.org/abs/1503.06189",
    "note": "Recnik et al. 2015, IEEE ASAP Conference"},
    {"title": "Coaxing Cosmic 21 cm Fluctuations from the Polarized Sky using m-mode Analysis",
    "url": "https://arxiv.org/abs/1401.2095",
    "note": "Shaw et al. 2015, Phys. Rev. D 91, 083514"},
    {"title": "Managing Hardware Configurations and Data Products for the Canadian Hydrogen Intensity Mapping Experiment",
    "url": "https://arxiv.org/abs/1410.8418",
    "note": "Hincks, Shaw & CHIME Collaboration, 2015, ASPC, 495, 523"},
    {"title": "Canadian Hydrogen Intensity Mapping Experiment (CHIME) Pathfinder",
    "url": "https://arxiv.org/abs/1406.2288",
    "note": "Bandura et al. 2014, Proc. SPIE, 9145, 914522"},
    {"title": "Calibrating CHIME, A New Radio Interferometer to Probe Dark Energy",
    "url": "https://arxiv.org/abs/1406.2267",
    "note": "Newburgh et al. 2014, Proc. SPIE, 9145, 91454V"},
    {"title": "A Radio-Frequency-over-Fiber link for large-array radio astronomy applications",
    "url": "https://arxiv.org/abs/1308.5481",
    "note": "Mena et al. 2013, Journal of Instrumentation, 8 T10003"},
    {"title": "All-Sky Interferometry with Spherical Harmonic Transit Telescopes",
    "url": "https://arxiv.org/abs/1302.0327",
    "note": "Shaw et al. 2013, Astrophysical Journal, 781, 57"}
]